### ISSUE TITLE
Duplicate --input option in documentation or command example

### ISSUE THREAD

**Issue by hossein-haeri** [jhu-dvrk/dvrk-readthedocs#2]
There's a small issue with the command example where the --input option is duplicated:

vcs import --input --input https://raw.githubusercontent.com/jhu-saw/vcs/main/ros2-d

p.s. Thank you for the new docs, looks much better!

**Comment by adeguet1** [comment]
I had already moved the ros1 and ros2 files (now under software/compilation).  Thanks for the report.
